### ISSUE TITLE
NPC Army feature clarification

### ISSUE THREAD

**Issue by TylorBane** [GrimKriegor/assistant#2]
i was wondering weather or not you could provide a little more information on how the npc army works? it just says "let you controle a group of npc's" and doesnt clearify wether they have to be pre-spawned for the commands to work. i plan on using this nifty little guy to be my right hand man when it comes to keeping my server in check and i was wondering how to get this set of body guards that could walk me around like a badass on my server. thanks

**Comment by GrimKriegor** [comment]
Hello Tylor, sorry for the late response. Glad there is still people using the Assistant.

Once you activate the npc army skill it will change the relationship of all your NPCs and make them follow you by default, they do not need to be pre-spawned and it is advised to only spawn them after the skill is running to prevent being attacked by the hostile ones.

Additionally, I have just realized that while not documented, you can use your Right Mouse Key to force them to engage in attack regardless if they have a target or not. (This creates a most badass display when using Vortigaunts or Fast Zombies 8D)

I hope I was able to clarify. 
Have fun with that little ball of death and destruction.

**Comment by TylorBane** [comment]
ah, right... so ah... I've gotten into "editing" at least... e2's and i was wondering if it was at all possible to add some of the really cool weapon e2's that I've... "collected"

**Comment by GrimKriegor** [comment]
Sure thing, the only limitation I'm seeing is the huge amount of OPs it takes to run a few features at the same time and even running thru the ever increascing codebase every cycle. The Assistant can always use a bunch of new skills ;)

**Comment by TylorBane** [comment]
so ah, want me to just put the .txt files of the e2's on dropbox and pop you the links?

**Comment by TylorBane** [comment]
oh and, isn't there a way to "sub-class" things in e2? so that it wont look at that set of code till it needs it?

**Comment by GrimKriegor** [comment]
Unfortunately I haven't had much motivation or time to work on features or even play Garry's Mod since 2011, only updating the assistant to keep compatibility with Wiremod updates. I would recomend you fork the project and try implementing them yourself, I could pop ingame and try help you troubleshoot or refine them from time to time :)

About optimizing the code, on late 2010 I exhausted all means I had to optimize it, even thought about using "signals" (if i remember correctly) to share the computing between a few chips while having a main one in control, at the time I dont think there was a way to "sub-class" portions of the code, it would be awesome if there was now.

Anyway, please do share the chips and ideas. they might spark some interest back into Gmod for me.
Feel free to add me on Steam "Grim Kriegor".
Also I still have my server going @ won.zalkeen.tk, if you need a testbed.
